language: ruby
cache: bundler
rvm:
- 2.1.0
branches:
  only:
  - master
script:
- bundle exec rake travis:script
after_success:
- bundle exec rake travis:after_success
before_install:
- openssl aes-256-cbc -K $encrypted_cda326ff967d_key -iv $encrypted_cda326ff967d_iv
  -in deploy_key.enc -out ~\/.ssh/deploy_key -d
